apiVersion: v1
kind: Service
metadata:
  name: apigwservice
  namespace: test
spec:
  selector:
    app: apigw
  ports:
    - port: 6040
      targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: identityserver
  namespace: test
spec:
  selector:
    app: identityserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  #type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapi
  namespace: test
spec:
  selector:
    app: sampleapi
  ports:
    - port: 80
      targetPort: 80
